name: test

on: [ push ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/checkout@v2
        with:
          repository: smogon/pokemon-showdown
          path: pokemon-showdown
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - run: npm start --prefix pokemon-showdown > out.log 2>&1 &
      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 5.0.x
      - run: dotnet build
      - run: tail -f -n+1 out.log | grep -qe "now listening"
      - run: dotnet test
